# Comfy Lotus 模型配置
model_name: "Comfy-Org/lotus"
model_type: "Comfy"
display_name: "Comfy Lotus Model"
disk_size: 200
system_disk_size: 200  # 兼容批量生成系统
deployment_name: "comfy-lotus"
model_image: "m-comfy-lotus-test"
artifact_name: "ComfyLotusImage"
source_image_id: "m-comfy-lotus-base-image"
timeout: 7200
gpu_type: "PPU"  # 批量生成系统使用
support_min_gpu_amount: 1
support_max_gpu_amount: 1
is_vision_model: false
is_fp8_model: false
is_deepseek_fp8_ppu_model: false
support_public_access: true
gpu_configs:
  - gpu_type: "Comfy-Lotus_PPU"
    hardware: "PPU810E"
    label: "P16EN"
    zones:
      - cn-wulanchabu-a
      - cn-beijing-d
      - cn-shanghai-f
      - cn-hangzhou-b
      - ap-southeast-1a
      - ap-southeast-1b
      - ap-southeast-1c
type: "ecs"
enabled: true