# 默认配置（用于批量生成系统）
defaults:
  system_disk_size: 450
  support_min_gpu_amount: 1
  support_max_gpu_amount: 1
  is_vision_model: false
  is_fp8_model: false
  is_deepseek_fp8_ppu_model: false
  support_public_access: true
  replicas: 1
  timeout: 7200
  type: "ecs"
  enabled: true

# 批量生成配置
batch_generator:
  service_name_prefix: "comfyui"
  template_dir: "templates"
  output_dir: "generated"
  enable_import: false
  max_concurrent_imports: 3