version: '3.8'

services:
  comfyui:
    container_name: comfy-ui
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8188:8188"
    volumes:
      - /root/storage/models:/root/ComfyUI/models
      - /root/storage/output:/root/ComfyUI/output
      - /root/storage/user_scripts:/root/ComfyUI/user_scripts
      - /root/storage/user:/root/ComfyUI/user
      - /root/storage/input:/root/ComfyUI/input
      - /root/storage/custom_nodes:/root/ComfyUI/custom_nodes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


